[MAINTENANCE] added readme for each lambda
provectus/data-quality-gate pull request #114
Opened 2023-08-07 10:31 UTC by bvolodarskiy

2023-08-07 12:27 UTC, egorodov approved these changes
LGTM

2023-08-14 21:56 UTC, a-chumagin requested changes
I made review for one file but my comments are actual for all new Readme

2023-08-14 21:56 UTC, a-chumagin commented on functions/allure_report/README.md
> +great-expectations
use unordered list format

2023-08-14 21:56 UTC, a-chumagin commented on functions/allure_report/README.md
> +Output: allure results in json format
use line breaks

2023-08-14 21:56 UTC, a-chumagin commented on functions/allure_report/README.md
> +
use line breaks

2023-08-14 21:56 UTC, a-chumagin commented on functions/allure_report/README.md
> +
better to use format `![Tux, the Linux mascot](/assets/images/tux.png)`

2023-08-15 10:26 UTC, oksanagorbachenko approved these changes

2023-08-20 20:27 UTC, a-chumagin approved these changes

2023-08-20 22:29 UTC, a-chumagin approved these changes
LGTM

2023-08-21 13:02 UTC, merged