optimized allure docker
provectus/data-quality-gate pull request #34
Opened 2023-02-10 13:45 UTC by bvolodarskiy

2023-02-13 08:53 UTC, egorodov approved these changes

2023-02-13 09:56 UTC, a-chumagin requested changes

2023-02-13 09:56 UTC, a-chumagin commented on functions/allure_report/Dockerfile
> +RUN yum install -y \
You do not need a newline here 
`yum install -y wget`

2023-02-13 13:17 UTC, a-chumagin commented on functions/allure_report/Dockerfile
> +RUN yum install -y wget
Also will be better to delete zip files after unpack 
`RUN mkdir allure && curl https://github.com/allure-framework/allure2/releases/download/2.14.0/allure-2.14.0.zip -O -L -C - \
&& unzip allure-2.14.0.zip -d allure && rm allure-2.14.0.zip \
&& curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -O -L -C -\
&& unzip awscli-exe-linux-x86_64.zip && rm awscli-exe-linux-x86_64.zip`

2023-02-14 08:57 UTC, a-chumagin approved these changes
LGTM

2023-02-14 10:24 UTC, merged